### ISSUE TITLE
Tag HTML sendo fechada como XHTML

### ISSUE THREAD

**Issue by MorrisRuschel** [vagnerzezo/listaJavascript#1]
Quando utilizamos o `<!DOCTYPE html>` no início do código isso significa que estamos usando o HTML e não XHTML;
Somente no XHTML (_antigo_) fechamos tags que "não tem fim".

**De**
`<input type="text" placeholder="Inclua um item na lista" />`
**Para**
`<input type="text" placeholder="Inclua um item na lista">`

**Comment by vagnerzezo** [comment]
Muito obrigado pelo report.

Ajustes realizados
